using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RazorpayPaymentGateway.Domain.Entities
{
    /// <summary>
    /// Represents the response returned after creating an order in the payment system.
    /// </summary>
    public class OrderResponse
    {
        /// <summary>
        /// Gets or sets the unique identifier of the order generated by Razorpay.
        /// </summary>
        public string OrderId { get; set; }

        /// <summary>
        /// Gets or sets the Razorpay API key used for processing the payment.
        /// </summary>
        public string RazorpayKey { get; set; }

        /// <summary>
        /// Gets or sets the total amount for the order in the original currency format (e.g., INR).
        /// </summary>
        public decimal Amount { get; set; }
    }


}
